//! Mechanical Bend rendering. Semantic decisions happen in `ir`.
use crate::ir::{self, Expr, Primitive};
use std::collections::BTreeSet;

const PRELUDE: &str = r#"# Generated by scheme-bend. Do not edit this prelude by hand.
# Lists are immutable. `car`/`cdr` on Nil use a documented total sentinel.
type SchemeList:
  Nil
  Cons { head, tail }

def scheme_car(xs):
  match xs:
    case SchemeList/Cons:
      return xs.head
    case SchemeList/Nil:
      return +0

def scheme_cdr(xs):
  match xs:
    case SchemeList/Cons:
      return xs.tail
    case SchemeList/Nil:
      return SchemeList/Nil

def scheme_null(xs):
  match xs:
    case SchemeList/Nil:
      return 1
    case SchemeList/Cons:
      return 0

"#;

pub fn emit(program: &ir::Program) -> String {
    let globals = program
        .definitions
        .iter()
        .filter(|d| d.params.is_empty())
        .map(|d| d.name.clone())
        .collect::<BTreeSet<_>>();
    let mut out = PRELUDE.to_owned();
    let mut emitter = Emitter::default();
    for definition in &program.definitions {
        let params = definition
            .params
            .iter()
            .map(|p| mangle(p))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("def {}({params}):\n", mangle(&definition.name)));
        emitter.emit_return(&definition.body, 1, &globals, &mut out);
        out.push('\n');
    }
    out.push_str("def main():\n");
    match &program.body {
        Some(body) => emitter.emit_return(body, 1, &globals, &mut out),
        None => out.push_str("  return +0\n"),
    }
    out
}

#[derive(Default)]
struct Emitter {
    next_temp: usize,
}
impl Emitter {
    fn temp(&mut self) -> String {
        let name = format!("scheme_tmp_{}", self.next_temp);
        self.next_temp += 1;
        name
    }
    fn emit_return(
        &mut self,
        expr: &Expr,
        depth: usize,
        globals: &BTreeSet<String>,
        out: &mut String,
    ) {
        let pad = "  ".repeat(depth);
        match expr {
            Expr::Let { bindings, body } => {
                for (name, value) in bindings {
                    let value = self.emit_value(value, depth, globals, out);
                    out.push_str(&format!("{pad}{} = {value}\n", mangle(name)));
                }
                self.emit_return(body, depth, globals, out);
            }
            Expr::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let condition = self.emit_value(condition, depth, globals, out);
                out.push_str(&format!("{pad}if {condition}:\n"));
                self.emit_return(then_branch, depth + 1, globals, out);
                out.push_str(&format!("{pad}else:\n"));
                self.emit_return(else_branch, depth + 1, globals, out);
            }
            _ => {
                let value = self.emit_value(expr, depth, globals, out);
                out.push_str(&format!("{pad}return {value}\n"));
            }
        }
    }
    fn emit_value(
        &mut self,
        expr: &Expr,
        depth: usize,
        globals: &BTreeSet<String>,
        out: &mut String,
    ) -> String {
        let pad = "  ".repeat(depth);
        match expr {
            Expr::Number(n) => signed_literal(*n),
            Expr::Bool(true) => "1".into(),
            Expr::Bool(false) => "0".into(),
            Expr::Nil => "SchemeList/Nil".into(),
            Expr::Var(name) if globals.contains(name) => format!("{}()", mangle(name)),
            Expr::Var(name) => mangle(name),
            Expr::Call { callee, args } => {
                let args = args
                    .iter()
                    .map(|arg| self.emit_value(arg, depth, globals, out))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}({args})", mangle(callee))
            }
            Expr::Primitive { op, args } => {
                let args = args
                    .iter()
                    .map(|arg| self.emit_value(arg, depth, globals, out))
                    .collect::<Vec<_>>();
                render_primitive(*op, &args)
            }
            Expr::Cons(head, tail) => {
                let head = self.emit_value(head, depth, globals, out);
                let tail = self.emit_value(tail, depth, globals, out);
                format!("SchemeList/Cons {{ head: {head}, tail: {tail} }}")
            }
            Expr::Car(value) => {
                let value = self.emit_value(value, depth, globals, out);
                format!("scheme_car({value})")
            }
            Expr::Cdr(value) => {
                let value = self.emit_value(value, depth, globals, out);
                format!("scheme_cdr({value})")
            }
            Expr::Null(value) => {
                let value = self.emit_value(value, depth, globals, out);
                format!("scheme_null({value})")
            }
            Expr::Let { bindings, body } => {
                for (name, value) in bindings {
                    let value = self.emit_value(value, depth, globals, out);
                    out.push_str(&format!("{pad}{} = {value}\n", mangle(name)));
                }
                self.emit_value(body, depth, globals, out)
            }
            Expr::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let condition = self.emit_value(condition, depth, globals, out);
                let result = self.temp();
                out.push_str(&format!("{pad}if {condition}:\n"));
                let then_value = self.emit_value(then_branch, depth + 1, globals, out);
                out.push_str(&format!(
                    "{}{} = {then_value}\n",
                    "  ".repeat(depth + 1),
                    result
                ));
                out.push_str(&format!("{pad}else:\n"));
                let else_value = self.emit_value(else_branch, depth + 1, globals, out);
                out.push_str(&format!(
                    "{}{} = {else_value}\n",
                    "  ".repeat(depth + 1),
                    result
                ));
                result
            }
        }
    }
}
fn signed_literal(n: i64) -> String {
    if n >= 0 {
        format!("+{n}")
    } else {
        n.to_string()
    }
}
fn render_primitive(op: Primitive, args: &[String]) -> String {
    let symbol = match op {
        Primitive::Add => "+",
        Primitive::Sub => "-",
        Primitive::Mul => "*",
        Primitive::Div => "/",
        Primitive::Eq => "==",
        Primitive::Lt => "<",
        Primitive::Gt => ">",
        Primitive::Le => "<=",
        Primitive::Ge => ">=",
    };
    format!("({} {symbol} {})", args[0], args[1])
}
pub fn mangle(name: &str) -> String {
    let mut result = String::from("s_");
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            result.push(ch);
        } else {
            result.push_str(&format!("_{}_,", ch as u32));
        }
    }
    result.replace(',', "")
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn mangles_scheme_punctuation() {
        assert_eq!(mangle("tree-sum?"), "s_tree_45_sum_63_");
    }
    #[test]
    fn emits_signed_i24_literals() {
        assert_eq!(signed_literal(-3), "-3");
        assert_eq!(signed_literal(3), "+3");
    }
}
