//! Mechanical Bend rendering. Semantic decisions happen in `ir`.
use crate::ir::{self, Expr, Primitive};
use std::collections::BTreeSet;

const PRELUDE: &str = r#"# Generated by scheme-bend. Do not edit this prelude by hand.
# Lists are immutable. `car`/`cdr` on Nil use a documented total sentinel.
type SchemeList:
  Nil
  Cons { head, tail }

def scheme_car(xs):
  match xs:
    case SchemeList/Cons:
      return xs.head
    case SchemeList/Nil:
      return +0

def scheme_cdr(xs):
  match xs:
    case SchemeList/Cons:
      return xs.tail
    case SchemeList/Nil:
      return SchemeList/Nil

def scheme_null(xs):
  match xs:
    case SchemeList/Nil:
      return 1
    case SchemeList/Cons:
      return 0

"#;

pub fn emit(program: &ir::Program) -> String {
    let globals = program
        .definitions
        .iter()
        .filter(|d| d.params.is_empty())
        .map(|d| d.name.clone())
        .collect::<BTreeSet<_>>();
    let mut out = PRELUDE.to_owned();
    let mut emitter = Emitter::default();
    for definition in &program.definitions {
        let params = definition
            .params
            .iter()
            .map(|p| mangle(p))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("def {}({params}):\n", mangle(&definition.name)));
        emitter.emit_return(&definition.body, 1, &globals, &mut out);
        out.push('\n');
    }
    out.push_str("def main():\n");
    match &program.body {
        Some(body) => emitter.emit_return(body, 1, &globals, &mut out),
        None => out.push_str("  return +0\n"),
    }
    out
}

#[derive(Default)]
struct Emitter {
    next_temp: usize,
}
impl Emitter {
    fn temp(&mut self) -> String {
        let name = format!("scheme_tmp_{}", self.next_temp);
        self.next_temp += 1;
        name
    }
    fn emit_return(
        &mut self,
        expr: &Expr,
        depth: usize,
        globals: &BTreeSet<String>,
        out: &mut String,
    ) {
        let pad = "  ".repeat(depth);
        match expr {
            Expr::Let { bindings, body } => {
                for (name, value) in bindings {
                    let value = self.emit_value(value, depth, globals, out);
                    out.push_str(&format!("{pad}{} = {value}\n", mangle(name)));
                }
                self.emit_return(body, depth, globals, out);
            }
            Expr::If {
                condition,
                then_branch,
                else_branch,
            } => {
                if let Some(name) = null_test_variable(condition) {
                    if let Some(plan) = plan_destructure(name, then_branch, else_branch) {
                        self.emit_list_match(&plan, then_branch, else_branch, depth, globals, out);
                        return;
                    }
                }
                let condition = self.emit_value(condition, depth, globals, out);
                out.push_str(&format!("{pad}if {condition}:\n"));
                self.emit_return(then_branch, depth + 1, globals, out);
                out.push_str(&format!("{pad}else:\n"));
                self.emit_return(else_branch, depth + 1, globals, out);
            }
            _ => {
                let value = self.emit_value(expr, depth, globals, out);
                out.push_str(&format!("{pad}return {value}\n"));
            }
        }
    }
    /// Emit `match` for a list test, binding every list the branch consumes.
    ///
    /// The natural lowering of
    ///     (if (null? xs) base (f (cdr xs) (... (car xs) ...)))
    /// calls the list accessors separately, so each list is used several times
    /// and HVM must duplicate it. HVM2 is eager, so duplicating a cons cell
    /// splits the node and its children immediately and the copy cascades down
    /// the spine: one spine copy per element makes traversal O(N^2).
    ///
    /// Each list is therefore bound once. Two cases matter:
    ///
    /// * Several lists walked in lockstep (a dot product, a merge) -- each gets
    ///   its own nested `match`.
    /// * Several elements of the *same* list consumed per call, written as
    ///   `(cdr (cdr x))` and friends -- handled by following the cdr spine:
    ///   bind `x.tail`, then `match` it to reach *its* head and tail, and so
    ///   on. That also amortises the per-element call, which is most of what a
    ///   list step costs.
    ///
    /// An exhausted list falls back to the accessor sentinels in its `Nil` arm,
    /// which is exactly what `scheme_car`/`scheme_cdr` return for `Nil`.
    fn emit_list_match(
        &mut self,
        plan: &Destructure,
        then_branch: &Expr,
        else_branch: &Expr,
        depth: usize,
        globals: &BTreeSet<String>,
        out: &mut String,
    ) {
        let names: Vec<String> = plan.roots.iter().map(|r| r.name.clone()).collect();
        self.emit_root(
            plan,
            &names,
            0,
            0,
            &[],
            then_branch,
            else_branch,
            depth,
            globals,
            out,
        );
    }

    /// Emits the spine `match` at `level` for root `root_idx`, then descends.
    #[allow(clippy::too_many_arguments)]
    fn emit_root(
        &mut self,
        plan: &Destructure,
        names: &[String],
        root_idx: usize,
        level: usize,
        bound: &[Binding],
        then_branch: &Expr,
        else_branch: &Expr,
        depth: usize,
        globals: &BTreeSet<String>,
        out: &mut String,
    ) {
        let root = &plan.roots[root_idx];
        let max_level = root.match_depth();
        let node = mangle(&root.node_name(level));
        let pad = "  ".repeat(depth);
        let inner = "  ".repeat(depth + 2);
        out.push_str(&format!("{pad}match {node}:\n"));
        out.push_str(&format!("{pad}  case SchemeList/Nil:\n"));
        if root.tested && level == 0 {
            // The list is empty: this is the branch the `if` selected.
            self.emit_return(then_branch, depth + 2, globals, out);
        } else {
            // The list ended partway down the spine. Every access from here on
            // sees Nil, which is what the accessor sentinels model.
            let mut nil_bound = bound.to_vec();
            nil_bound.extend(root.sentinels(root_idx, level));
            let body = substitute_accessors(else_branch, names, &nil_bound);
            self.emit_return(&body, depth + 2, globals, out);
        }
        out.push_str(&format!("{pad}  case SchemeList/Cons:\n"));
        let mut cons_bound = bound.to_vec();
        if root.head_depths.contains(&level) {
            let name = root.head_name(level);
            out.push_str(&format!("{inner}{} = {node}.head\n", mangle(&name)));
            cons_bound.push(Binding {
                root: root_idx,
                depth: level,
                head: true,
                value: Expr::Var(name),
            });
        }
        let descend = level < max_level;
        if descend || root.tail_depths.contains(&(level + 1)) {
            let name = root.node_name(level + 1);
            out.push_str(&format!("{inner}{} = {node}.tail\n", mangle(&name)));
            cons_bound.push(Binding {
                root: root_idx,
                depth: level + 1,
                head: false,
                value: Expr::Var(name),
            });
        }
        if descend {
            self.emit_root(
                plan,
                names,
                root_idx,
                level + 1,
                &cons_bound,
                then_branch,
                else_branch,
                depth + 2,
                globals,
                out,
            );
        } else if root_idx + 1 < plan.roots.len() {
            self.emit_root(
                plan,
                names,
                root_idx + 1,
                0,
                &cons_bound,
                then_branch,
                else_branch,
                depth + 2,
                globals,
                out,
            );
        } else {
            let body = substitute_accessors(else_branch, names, &cons_bound);
            self.emit_return(&body, depth + 2, globals, out);
        }
    }

    fn emit_value(
        &mut self,
        expr: &Expr,
        depth: usize,
        globals: &BTreeSet<String>,
        out: &mut String,
    ) -> String {
        let pad = "  ".repeat(depth);
        match expr {
            Expr::Number(n) => signed_literal(*n),
            Expr::Bool(true) => "1".into(),
            Expr::Bool(false) => "0".into(),
            Expr::Nil => "SchemeList/Nil".into(),
            Expr::Var(name) if globals.contains(name) => format!("{}()", mangle(name)),
            Expr::Var(name) => mangle(name),
            Expr::Call { callee, args } => {
                let args = args
                    .iter()
                    .map(|arg| self.emit_value(arg, depth, globals, out))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}({args})", mangle(callee))
            }
            Expr::Primitive { op, args } => {
                let args = args
                    .iter()
                    .map(|arg| self.emit_value(arg, depth, globals, out))
                    .collect::<Vec<_>>();
                render_primitive(*op, &args)
            }
            Expr::Cons(head, tail) => {
                let head = self.emit_value(head, depth, globals, out);
                let tail = self.emit_value(tail, depth, globals, out);
                format!("SchemeList/Cons {{ head: {head}, tail: {tail} }}")
            }
            Expr::Car(value) => {
                let value = self.emit_value(value, depth, globals, out);
                format!("scheme_car({value})")
            }
            Expr::Cdr(value) => {
                let value = self.emit_value(value, depth, globals, out);
                format!("scheme_cdr({value})")
            }
            Expr::Null(value) => {
                let value = self.emit_value(value, depth, globals, out);
                format!("scheme_null({value})")
            }
            Expr::Let { bindings, body } => {
                for (name, value) in bindings {
                    let value = self.emit_value(value, depth, globals, out);
                    out.push_str(&format!("{pad}{} = {value}\n", mangle(name)));
                }
                self.emit_value(body, depth, globals, out)
            }
            Expr::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let condition = self.emit_value(condition, depth, globals, out);
                let result = self.temp();
                out.push_str(&format!("{pad}if {condition}:\n"));
                let then_value = self.emit_value(then_branch, depth + 1, globals, out);
                out.push_str(&format!(
                    "{}{} = {then_value}\n",
                    "  ".repeat(depth + 1),
                    result
                ));
                out.push_str(&format!("{pad}else:\n"));
                let else_value = self.emit_value(else_branch, depth + 1, globals, out);
                out.push_str(&format!(
                    "{}{} = {else_value}\n",
                    "  ".repeat(depth + 1),
                    result
                ));
                result
            }
        }
    }
}
/// Recognises `(null? x)` where `x` is a plain variable.
fn null_test_variable(condition: &Expr) -> Option<&str> {
    match condition {
        Expr::Null(inner) => match &**inner {
            Expr::Var(name) => Some(name),
            _ => None,
        },
        _ => None,
    }
}

/// One list variable the emitter binds, and how far down its cdr spine the
/// branch reaches.
struct RootPlan {
    name: String,
    /// Chain depths (number of `cdr`s applied) at which a head is read.
    head_depths: Vec<usize>,
    /// Chain depths at which the tail is taken.
    tail_depths: Vec<usize>,
    /// True for the variable named by the test, whose `Nil` arm is the original
    /// then-branch rather than a sentinel fallback.
    tested: bool,
}

impl RootPlan {
    fn head_name(&self, level: usize) -> String {
        format!("{}_h{}", self.name, level)
    }
    /// The node at a chain depth: depth 0 is the variable itself.
    fn node_name(&self, level: usize) -> String {
        if level == 0 {
            self.name.clone()
        } else {
            format!("{}_t{}", self.name, level)
        }
    }
    /// The deepest spine `match` this root needs. A head at depth k needs the
    /// node at depth k matched; a tail at depth k needs depth k-1 matched.
    fn match_depth(&self) -> usize {
        let head = self.head_depths.iter().copied().max().unwrap_or(0);
        let tail = self
            .tail_depths
            .iter()
            .map(|k| k.saturating_sub(1))
            .max()
            .unwrap_or(0);
        head.max(tail)
    }
    /// What every access from `level` down evaluates to once the list is Nil.
    fn sentinels(&self, root: usize, level: usize) -> Vec<Binding> {
        let mut out = Vec::new();
        for depth in level..=self.match_depth() {
            out.push(Binding {
                root,
                depth,
                head: true,
                value: Expr::Number(0),
            });
        }
        for depth in (level + 1)..=(self.match_depth() + 1) {
            out.push(Binding {
                root,
                depth,
                head: false,
                value: Expr::Nil,
            });
        }
        out
    }
}

/// A resolved accessor chain, keyed by root index and `cdr` count.
#[derive(Clone)]
struct Binding {
    root: usize,
    depth: usize,
    head: bool,
    value: Expr,
}

struct Destructure {
    roots: Vec<RootPlan>,
}

/// How many extra lists to bind. Each adds a nested match and one more copy of
/// the body in its exhausted arm, so this is deliberately bounded.
const MAX_SECONDARIES: usize = 4;

/// Plans a destructuring `match`, or declines.
///
/// A variable is bound only when every use of it is the base of a `car`/`cdr`
/// chain and it is not touched in the nil branch: any other use would itself
/// need a copy, which is the cost this rewrite exists to remove.
fn plan_destructure(tested: &str, then_branch: &Expr, else_branch: &Expr) -> Option<Destructure> {
    // A variable bound by a `let` *inside* a branch is not in scope at the
    // `if`, so binding it with a hoisted match would reference it before it
    // exists.
    let mut inner_locals = Vec::new();
    collect_let_bound(then_branch, &mut inner_locals);
    collect_let_bound(else_branch, &mut inner_locals);

    let mut roots = vec![RootPlan {
        name: tested.to_owned(),
        head_depths: Vec::new(),
        tail_depths: Vec::new(),
        tested: true,
    }];
    let mut candidates = Vec::new();
    collect_list_roots(else_branch, &mut candidates);
    for candidate in candidates {
        if roots.len() > MAX_SECONDARIES {
            break;
        }
        if candidate == tested
            || inner_locals.contains(&candidate)
            || uses_variable(then_branch, &candidate)
            || !only_chained_uses(else_branch, &candidate)
        {
            continue;
        }
        roots.push(RootPlan {
            name: candidate,
            head_depths: Vec::new(),
            tail_depths: Vec::new(),
            tested: false,
        });
    }

    let names: Vec<String> = roots.iter().map(|r| r.name.clone()).collect();
    scan_depths(else_branch, &names, &mut roots);
    // Nothing is accessed: a plain `if` is simpler than a match.
    if roots
        .iter()
        .all(|r| r.head_depths.is_empty() && r.tail_depths.is_empty())
    {
        return None;
    }
    Some(Destructure { roots })
}

/// Resolves a `cdr` chain to (root index, number of `cdr`s).
fn resolve_tail(expr: &Expr, names: &[String]) -> Option<(usize, usize)> {
    match expr {
        Expr::Var(v) => names.iter().position(|n| n == v).map(|i| (i, 0)),
        Expr::Cdr(inner) => {
            let (i, k) = resolve_tail(inner, names)?;
            Some((i, k + 1))
        }
        _ => None,
    }
}

/// Resolves `(car chain)` / `(cdr chain)` to (root index, `cdr` count, is_head).
fn resolve_accessor(expr: &Expr, names: &[String]) -> Option<(usize, usize, bool)> {
    match expr {
        Expr::Car(inner) => resolve_tail(inner, names).map(|(i, k)| (i, k, true)),
        Expr::Cdr(inner) => resolve_tail(inner, names).map(|(i, k)| (i, k + 1, false)),
        _ => None,
    }
}

/// True when `expr` is `car`/`cdr` applied to a `cdr` chain rooted at `name`.
fn valid_chain(expr: &Expr, name: &str) -> bool {
    match expr {
        Expr::Car(inner) | Expr::Cdr(inner) => tail_chain_name(inner).as_deref() == Some(name),
        _ => false,
    }
}

fn tail_chain_name(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Var(v) => Some(v.clone()),
        Expr::Cdr(inner) => tail_chain_name(inner),
        _ => None,
    }
}

/// True when every occurrence of `name` is the base of a `car`/`cdr` chain.
fn only_chained_uses(expr: &Expr, name: &str) -> bool {
    if let Expr::Var(v) = expr {
        return v != name;
    }
    if matches!(expr, Expr::Car(_) | Expr::Cdr(_)) && valid_chain(expr, name) {
        return true;
    }
    children(expr).iter().all(|c| only_chained_uses(c, name))
}

/// Every variable appearing as the base of a `car`/`cdr` chain.
fn collect_list_roots(expr: &Expr, out: &mut Vec<String>) {
    if matches!(expr, Expr::Car(_) | Expr::Cdr(_)) {
        if let Some(name) = match expr {
            Expr::Car(inner) | Expr::Cdr(inner) => tail_chain_name(inner),
            _ => None,
        } {
            if !out.contains(&name) {
                out.push(name);
            }
        }
    }
    for child in children(expr) {
        collect_list_roots(child, out);
    }
}

/// Records, per root, the chain depths at which heads and tails are read.
fn scan_depths(expr: &Expr, names: &[String], roots: &mut [RootPlan]) {
    if let Some((i, k, is_head)) = resolve_accessor(expr, names) {
        let list = if is_head {
            &mut roots[i].head_depths
        } else {
            &mut roots[i].tail_depths
        };
        if !list.contains(&k) {
            list.push(k);
        }
        return;
    }
    for child in children(expr) {
        scan_depths(child, names, roots);
    }
}

fn children(expr: &Expr) -> Vec<&Expr> {
    match expr {
        Expr::Primitive { args, .. } | Expr::Call { args, .. } => args.iter().collect(),
        Expr::If {
            condition,
            then_branch,
            else_branch,
        } => vec![condition, then_branch, else_branch],
        Expr::Let { bindings, body } => bindings
            .iter()
            .map(|(_, v)| v)
            .chain(std::iter::once(&**body))
            .collect(),
        Expr::Cons(a, b) => vec![a, b],
        Expr::Car(v) | Expr::Cdr(v) | Expr::Null(v) => vec![v],
        Expr::Var(_) | Expr::Number(_) | Expr::Bool(_) | Expr::Nil => Vec::new(),
    }
}

/// Every variable bound by a `let` anywhere inside `expr`.
fn collect_let_bound(expr: &Expr, out: &mut Vec<String>) {
    match expr {
        Expr::Let { bindings, body } => {
            for (name, value) in bindings {
                out.push(name.clone());
                collect_let_bound(value, out);
            }
            collect_let_bound(body, out);
        }
        Expr::Primitive { args, .. } | Expr::Call { args, .. } => {
            for arg in args {
                collect_let_bound(arg, out);
            }
        }
        Expr::If {
            condition,
            then_branch,
            else_branch,
        } => {
            collect_let_bound(condition, out);
            collect_let_bound(then_branch, out);
            collect_let_bound(else_branch, out);
        }
        Expr::Cons(a, b) => {
            collect_let_bound(a, out);
            collect_let_bound(b, out);
        }
        Expr::Car(v) | Expr::Cdr(v) | Expr::Null(v) => collect_let_bound(v, out),
        Expr::Var(_) | Expr::Number(_) | Expr::Bool(_) | Expr::Nil => {}
    }
}

/// True when `name` occurs anywhere in `expr`.
fn uses_variable(expr: &Expr, name: &str) -> bool {
    match expr {
        Expr::Var(v) => v == name,
        Expr::Primitive { args, .. } | Expr::Call { args, .. } => {
            args.iter().any(|a| uses_variable(a, name))
        }
        Expr::If {
            condition,
            then_branch,
            else_branch,
        } => {
            uses_variable(condition, name)
                || uses_variable(then_branch, name)
                || uses_variable(else_branch, name)
        }
        Expr::Let { bindings, body } => {
            bindings.iter().any(|(_, v)| uses_variable(v, name)) || uses_variable(body, name)
        }
        Expr::Cons(a, b) => uses_variable(a, name) || uses_variable(b, name),
        Expr::Car(v) | Expr::Cdr(v) | Expr::Null(v) => uses_variable(v, name),
        Expr::Number(_) | Expr::Bool(_) | Expr::Nil => false,
    }
}

/// Replaces each accessor chain with the value planned for it.
fn substitute_accessors(expr: &Expr, names: &[String], bindings: &[Binding]) -> Expr {
    if let Some((root, depth, head)) = resolve_accessor(expr, names) {
        if let Some(b) = bindings
            .iter()
            .find(|b| b.root == root && b.depth == depth && b.head == head)
        {
            return b.value.clone();
        }
    }
    map_children(expr, &|child| substitute_accessors(child, names, bindings))
}

fn map_children(expr: &Expr, f: &dyn Fn(&Expr) -> Expr) -> Expr {
    match expr {
        Expr::Primitive { op, args } => Expr::Primitive {
            op: *op,
            args: args.iter().map(f).collect(),
        },
        Expr::Call { callee, args } => Expr::Call {
            callee: callee.clone(),
            args: args.iter().map(f).collect(),
        },
        Expr::If {
            condition,
            then_branch,
            else_branch,
        } => Expr::If {
            condition: Box::new(f(condition)),
            then_branch: Box::new(f(then_branch)),
            else_branch: Box::new(f(else_branch)),
        },
        Expr::Let { bindings, body } => Expr::Let {
            bindings: bindings.iter().map(|(n, v)| (n.clone(), f(v))).collect(),
            body: Box::new(f(body)),
        },
        Expr::Cons(a, b) => Expr::Cons(Box::new(f(a)), Box::new(f(b))),
        Expr::Car(v) => Expr::Car(Box::new(f(v))),
        Expr::Cdr(v) => Expr::Cdr(Box::new(f(v))),
        Expr::Null(v) => Expr::Null(Box::new(f(v))),
        leaf => leaf.clone(),
    }
}

fn signed_literal(n: i64) -> String {
    if n >= 0 {
        format!("+{n}")
    } else {
        n.to_string()
    }
}
fn render_primitive(op: Primitive, args: &[String]) -> String {
    let symbol = match op {
        Primitive::Add => "+",
        Primitive::Sub => "-",
        Primitive::Mul => "*",
        Primitive::Div => "/",
        Primitive::Eq => "==",
        Primitive::Lt => "<",
        Primitive::Gt => ">",
        Primitive::Le => "<=",
        Primitive::Ge => ">=",
    };
    format!("({} {symbol} {})", args[0], args[1])
}
/// Render a Scheme identifier as a Bend identifier.
///
/// Alphanumerics pass through; every other character is escaped as `Q<code>_`,
/// where `<code>` is its decimal code point. The escape marker `Q` is itself
/// escaped, so every `Q` in the output begins an escape.
///
/// The marker cannot be `_`. Bend rejects any top-level name containing `__`,
/// and an escape that begins or ends with `_` creates one in two ways: two
/// adjacent escapes (`a__b`), and the `s_` prefix followed by an escape (any
/// name starting with punctuation, such as `_a`). A leading alphanumeric marker
/// avoids both, and a trailing `_` terminates the variable-width code so a
/// code's digits cannot merge into a following digit.
///
/// Since a literal `Q` is escaped too, the code is uniquely decodable, so two
/// distinct Scheme names can never mangle to the same Bend name.
pub fn mangle(name: &str) -> String {
    let mut result = String::from("s_");
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() && ch != 'Q' {
            result.push(ch);
        } else {
            result.push('Q');
            result.push_str(&(ch as u32).to_string());
            result.push('_');
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn mangles_scheme_punctuation() {
        assert_eq!(mangle("tree-sum?"), "s_treeQ45_sumQ63_");
    }
    #[test]
    fn never_emits_the_double_underscore_bend_forbids() {
        // Bend rejects `__` in a top-level name. Escapes used to start and end
        // with `_`, so adjacent escapes, and the `s_` prefix followed by an
        // escape, both produced one.
        for name in ["a__b", "__", "_", "a_", "_a", "..", "a-b_c?", "??", "___"] {
            let mangled = mangle(name);
            assert!(!mangled.contains("__"), "{name} -> {mangled}");
        }
    }
    #[test]
    fn escapes_stay_distinguishable() {
        // A code's digits must not merge into a following digit: `_` is 95 and
        // tab is 9, so without a terminator these two could collide.
        assert_ne!(mangle("_b"), mangle("\u{9}b"));
        assert_ne!(mangle("a_b"), mangle("a95b"));
        // The marker itself must be escaped, or `Q` and `Q45` would collide.
        assert_ne!(mangle("Q"), mangle("Q45"));
    }
    #[test]
    fn emits_signed_i24_literals() {
        assert_eq!(signed_literal(-3), "-3");
        assert_eq!(signed_literal(3), "+3");
    }
}
